export enum StorageKeys {
    APP_NAME = 'app_name',
    APP_VERSION = 'app_version',
    APP_METADATA = 'app_metadata',
    IS_USER_SUBSCRIBED = 'isUserSubscribed',
    CLIENT_ID = 'clientId',
    CHECKSUM = 'checksum',
    CONFIG = 'config',
    USER_CONSUMER_TOKEN = 'USER_CONSUMER_TOKEN',
    USER_PROFILE_TOKEN = 'USER_PROFILE_TOKEN',
    USER_DATA = 'USER_DATA',
    ERRORCODE = 'errorCode',
    SPLASH = 'splash',
    LABELS = 'labels',
    APP_BACKGROUND_COLOR = 'appBackgroundColor',
    FAVOURITES = 'favourites',
    RECENT_SEARCH = 'recentSearch',
    SESSIONID = 'sessionID',
    DEVICEINFO = 'deviceInfo',
    SELECTED_AUDIO_MENU = 'selectedAudioMenu',
    SELECTED_QUALITY_MENU = 'selectedQualityMenu',
    SELECTED_SUBTITLE_MENU = 'selectedSubtitleMenu',
    RECENTLY_WATCHED = 'recentlyWatched',
    PREVIEW_DIMENSIONS = 'previewDimensions',
    USER_ID = 'USER_ID',
    AXIOS_CACHED_RESPONSES = 'AxiosCachedResponses',
    ENTRIES_RESPONSE = 'EntriesResponse',
    USER_NAME = 'USER_NAME',
    SERVER_TIME = 'SERVER_TIME',
    LOGIN_INFO = 'LOGIN_INFO',
    PROFILE = 'PROFILE',
    PROFILE_ID = 'PROFILE_ID',
    COUNTRY_INFO = 'country_info',
    LOCALE = 'locale',
    SESSION_START_TIME = 'session_start_time',
    USER_EMAIL = 'user_email',
    AUTO_PLAY_VIDEO = 'auto_play_video',
    RECREATE_SIDEBAR = 'recreate_sidebar',
    ANALYTICS_SERVICES = 'analytics_services',
    /* The dependencies that when changed should cause a remmapping of the configuration on entries fetch.
  It will consist of the the previous (if any) entries checksum value and all other values that affect the filtering of entries in any manner.
   */
    CONFIGURATION_DEPENDENCIES = 'CONFIGURATION_DEPENDENCIES',
    ENGAGE_CLIENT_ID = 'Engage_Client_ID',
}
